In [3]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt
dataset=load_dataset("lukebarousse/data_jobs")
df=dataset['train'].to_pandas()

c:\Users\DELL\anaconda3\1\envs\py11\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [3]:
df.tail()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [4]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
727495,Senior Data Engineer,Senior Software Engineer (Data Platform),"Milton, ON, Canada",via WJHL Jobs,Full-time,False,Canada,2023-03-20 21:24:02,True,False,Canada,NaN,NaN,NaN,Ripple Labs,"['java', 'scala', 'python', 'sql', 'aws', 'spa...","{'analyst_tools': ['excel'], 'cloud': ['aws'],..."
772533,Data Engineer,Data Engineer,"Canberra ACT, Australia",via LinkedIn,Contractor,False,Australia,2023-01-16 01:25:27,False,False,Australia,NaN,NaN,NaN,Green Light Worldwide,"['nosql', 'mongodb', 'mongodb', 'postgresql', ...","{'analyst_tools': ['visio'], 'cloud': ['snowfl..."
477469,Data Analyst,Data Analyst,Anywhere,via Indeed,Full-time,True,"California, United States",2023-02-23 14:00:56,False,False,United States,NaN,NaN,NaN,Cox Toyota,"['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
167612,Data Analyst,Medicaid Data Analyst,Anywhere,via LinkedIn,Contractor,True,"Illinois, United States",2023-07-06 15:04:51,True,False,United States,NaN,NaN,NaN,Apex Systems,"['r', 'python', 'sas', 'sas', 'sql', 'spss', '...","{'analyst_tools': ['sas', 'spss', 'excel', 'po..."
321770,Data Analyst,Data Security Analyst- Remote,"Austin, TX",via Trabajo.org,Full-time,False,"Texas, United States",2023-10-27 17:01:00,True,False,United States,NaN,NaN,NaN,PriceSenz,NaN,NaN
681371,Machine Learning Engineer,Machine Learning Engineer,"Stockholm, Sweden",via LinkedIn,Contractor,False,Sweden,2023-05-04 10:30:03,False,False,Sweden,NaN,NaN,NaN,TDA Creative,"['python', 'gcp', 'pyspark']","{'cloud': ['gcp'], 'libraries': ['pyspark'], '..."
441268,Data Scientist,Data Scientist,"Columbus, OH",via Indeed,Full-time,False,"Illinois, United States",2023-03-08 16:04:55,False,False,United States,year,97500.0,NaN,Devcare Solutions,"['r', 'python', 'sas', 'sas', 'spss']","{'analyst_tools': ['sas', 'spss'], 'programmin..."
656885,Data Engineer,Data Engineer,United States,via BeBee,Full-time,False,"Illinois, United States",2023-08-01 10:13:22,False,True,United States,NaN,NaN,NaN,Arthur Lawrence,"['python', 'powershell', 'go', 'azure', 'datab...","{'cloud': ['azure', 'databricks'], 'libraries'..."
670554,Software Engineer,Software Engineer,"Belfast, UK",via LinkedIn,Full-time,False,United Kingdom,2023-11-25 10:11:40,False,False,United Kingdom,NaN,NaN,NaN,BT Group,"['java', 'sql', 'python', 'go', 'nosql', 'scal...","{'cloud': ['oracle', 'bigquery'], 'libraries':..."
620238,Senior Data Analyst,"Senior Data Analyst, Marketing Operations","Watertown, MA",via BeBee,Full-time,False,"New York, United States",2023-12-03 12:00:24,True,True,United States,NaN,NaN,NaN,Eleanor Health,"['sql', 'python']","{'programming': ['sql', 'python']}"

In [4]:
dataset=load_dataset('lukebarousse/data_jobs')
df_original=dataset['train'].to_pandas()

In [5]:
df_altered=df_original
df_altered

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [6]:
df_altered.loc[:5,'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [7]:
median_salary=df_altered['salary_year_avg'].median()
median_salary

np.float64(115000.0)

In [8]:
df_altered['salary_year_avg']=df_altered['salary_year_avg'].fillna(median_salary)
df_altered.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [9]:
df_original.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [10]:
id(df_original)

2111530267856

In [11]:
id(df_altered)

2111530267856

In [12]:
dataset=load_dataset('lukebarousse/data_jobs')
df_original=dataset['train'].to_pandas()

In [19]:
df_altered=df_original.copy()

In [20]:
id(df_original)

2111529399120

In [21]:
id(df_altered)

2111529394320

In [23]:
median_salary=df_altered['salary_year_avg'].median()
df_altered['salary_year_avg']=df_altered['salary_year_avg'].fillna(median_salary)
df_altered.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [24]:
df_original.loc[:5,'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64